// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/[...]').default>>>>
    }
    '/api/auth/signin': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/signin.post').default>>>>
    }
    '/api/nodes/:name': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/nodes/[name]/index.delete').default>>>>
    }
    '/api/nodes/:name/toggle': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/nodes/[name]/toggle.put').default>>>>
    }
    '/api/nodes': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/nodes/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/nodes/index.post').default>>>>
    }
    '/api/publish': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/publish.post').default>>>>
    }
    '/api/publish/batch': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/publish/batch.post').default>>>>
    }
    '/api/record/:id': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/record/[id]').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}